### ISSUE TITLE
Why "Witness"?

### ISSUE THREAD

**Issue by davegurnell** [underscoreio/shapeless-guide#13]
From @d6y:

Page 58

I feel there needs some kind of motivation or intuition for the use of the word Witness. One to ask @milessabin about?

**Comment by milessabin** [comment]
It's a technical term in logic and mathematics ... see the [wikipedia entry](https://en.wikipedia.org/wiki/Witness_(mathematics)). The description under "Henkin witness" is probably the closest to what's going on in shapeless: a singleton type can be thought of as a predicate which is true or not of all values; by definition it's only true of one particular value, and that value is then the unique witness for the truth of the statement that there is at least one value of which the predicate holds.

**Comment by davegurnell** [comment]
Thanks @milessabin. I added a super minimal footnote in 365befc that links to your Wikipedia entry and (hopefully) addresses the ticket. I'm happy to elaborate further if you think it necessary.

**Comment by milessabin** [comment]
LGTM :-)
