### ISSUE TITLE
5.4 "Deriving coproduct instances with LabelledGeneric" is blank

### ISSUE THREAD

**Issue by cb372** [underscoreio/shapeless-guide#24]
In the distributed PDF and HTML, the body of section 5.4 is missing. There's only a title.

I'm not sure what the problem was, but I've just tried building the book locally and it worked fine. So just doing a rebuild should be enough to fix it.

**Comment by davegurnell** [comment]
Thanks! I think that's a problem with that print copy. Must've passed me by
when I was looking through the proofs for the printers.

**Comment by davegurnell** [comment]
Regenerating the file in a2616df4 fixed the problem.
