### ISSUE TITLE
Syntax highlighting issue on page 81, 6.4.1 'Selecting fields'

### ISSUE THREAD

**Issue by zarthross** [underscoreio/shapeless-guide#30]
The `'` in symbol seemed to mess up the highlighter.

![image](https://cloud.githubusercontent.com/assets/1111592/22183917/56200faa-e08e-11e6-9b87-4f22fa443cdf.png)

**Comment by davegurnell** [comment]
That must be a bug in the LaTeX package we use for syntax highlighting. I'm happy to take suggestions/contributions to fix it but I don't have bandwidth to look into it on my own.
