### ISSUE TITLE
getWrappedValue to enforces arity assertion

### ISSUE THREAD

**Issue by srp** [underscoreio/shapeless-guide#32]
Section 4.3 ("Chaining dependent functions") introduces the `getWrappedValue` method by asserting: _we wanted to summon a Generic for a case class of exactly one field_.

However, the given solution does not enforce that assertion:

```scala
scala> case class Wrapper2(v: Long, v2: Long)
defined class Wrapper2

scala> foo.Foo.getWrappedValue(Wrapper2(42,12))
res2: Long = 42
```

Wouldn't it be better (and simpler) to use `HNil` instead of `Tail <: HList`, as that will enforce the assertion that the case class has only a single field, eg:

```scala
def getWrappedValue[A, Repr <: HList, Head](in: A)(
    implicit gen: Generic.Aux[A, Repr],
    isHCons: IsHCons.Aux[Repr, Head, HNil]
): Head = gen.to(in).head
```

Now:

```scala
scala> case class Wrapper(v: Long)
defined class Wrapper

scala> foo.Foo.getWrappedValue(Wrapper(42))
res1: Long = 42

scala> case class Wrapper2(v: Long, v2: Long)
defined class Wrapper2

scala> foo.Foo.getWrappedValue(Wrapper2(42,12))
<console>:14: error: could not find implicit value for parameter isHCons: shapeless.ops.hlist.IsHCons.Aux[Repr,Head,shapeless.HNil]
       foo.Foo.getWrappedValue(Wrapper2(42,12))
```

Huge thanks for this guide, learning a lot!

**Comment by Jasper-M** [comment]
This already got fixed: https://github.com/underscoreio/shapeless-guide/pull/20
You probably have an outdated version.

**Comment by davegurnell** [comment]
Thanks for the spot, @srp. Keep 'em coming! 

Also, grab an updated PDF from the `dist` folder!
