### ISSUE TITLE
Download/buy page should be https

### ISSUE THREAD

**Issue by ryan-williams** [underscoreio/shapeless-guide#37]
Chrome (rightfully) doesn't like me entering credit-card details onto an `http://` page like http://underscore.io/books/shapeless-guide/:

![](https://cl.ly/303x0y3x130J/Screen%20Shot%202017-03-15%20at%209.55.52%20PM.png)

It's wrong to think that subsequent https reqs from an http page can be considered secure; no guarantees can be made about the authenticity of the JS running on an http page.

**Comment by davegurnell** [comment]
Thanks for the spot. I'll look into it. Note that, as a workaround, you can load the Underscore web site under HTTPS.

**Comment by ryan-williams** [comment]
Thanks, that was an easy work-around; I'd say just adding the relevant "s" to the link in this repo's GitHub description would constitute fixing this issue afaic

**Comment by davegurnell** [comment]
Sounds good.

**Comment by davegurnell** [comment]
The README now contains https links. I think Richard must've fixed it.
