### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lolgab** [underscoreio/shapeless-guide#40]
Page 17:

IN the blue rectangle
"Other product types
It’s worth noting that Scala tuples are actually case classes, so Generic
works with them just fine:"

Noting without 'h'

**Comment by davegurnell** [comment]
Thanks for submitting this issue. However, the text is actually correct as is. My intention is actually to use "noting" here. "It's worth noting ..." is like saying "Note that ..." or "It is worthy of note that...".
