### ISSUE TITLE
Use "summoner" in section 8.3

### ISSUE THREAD

**Issue by radusw** [underscoreio/shapeless-guide#43]
In the random value generator case study a "summoner" method should be added and the created instance used to generate the random values in the following examples.

```scala
...
object Random { 
  def apply[A](implicit r: Random[A]): Random[A] = r
}
...
val rc = Random[Cell]
for(i <- 1 to 5) println(rc.get)
```

**Comment by davegurnell** [comment]
Thanks for submitting this. I'll add this to my TODO list for the next time I fold errata into the book.
